import { POSTAL_CODE } from '../constants'

export default {
  postalCodeFrom: POSTAL_CODE,
  fields: [
    {
      field: 'postalCode',
      label: 'postalCode',
      required: true,
      mask: '99999',
      regex: '^\\d{5}$',
      postalCodeAPI: true,
      forgottenURL: 'http://www.sepomex.gob.mx/servicioslinea/paginas/ccpostales.aspx',
      size: 'small',
    },
    {
      field: 'street',
      label: 'street',
      required: true,
      size: 'xlarge',
    },
    {
      field: 'number',
      label: 'exteriorNumber',
      required: true,
      size: 'mini',
    },
    {
      field: 'complement',
      label: 'interiorNumber',
      size: 'large',
    },
    {
      field: 'neighborhood',
      label: 'colony',
      required: true,
      size: 'xlarge',
    },
    {
      field: 'city',
      label: 'municipalityDelegation',
      required: true,
      size: 'xlarge',
    },
    {
      field: 'state',
      label: 'state',
      required: true,
      size: 'xlarge',
      isUpperCase: false,
      options: [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de México',
        'Coahuila De Zaragoza',
        'Colima',
        'Durango',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'México',
        'Michoacán de Ocampo',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
      ],
    },
  ],
}
