apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: address-form
  description: "A React component that renders VTEX's address forms "
  tags:
    - typescript
    - react
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: checkout_ui*
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/address-form
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: CK8TDYV0
    vtex.com/platform-flow-id: Shopper#4
spec:
  system: checkout
  lifecycle: stable
  owner: checkout-experience
  type: library
  dependsOn: []
  subcomponentOf: checkout-ui
