export const POSTAL_CODE = 'POSTAL_CODE'
export const ONE_LEVEL = 'STATE'
export const TWO_LEVELS = 'CITY'
export const THREE_LEVELS = 'NEIGHBORHOOD'

export const POSTAL_CODE_FROM_TYPES = [
  POSTAL_CODE,
  ONE_LEVEL,
  TWO_LEVELS,
  THREE_LEVELS,
]

export const EEMPTY = 'ERROR_EMPTY_FIELD'
export const EADDRESSTYPE = 'ERROR_INVALID_ADDRESS_TYPE'
export const ENOTOPTION = 'ERROR_VALUE_IS_NOT_AN_OPTION'
export const ECOUNTRY = 'ERROR_INVALID_COUNTRY_CODE'
export const EGEOCOORDS = 'ERROR_INVALID_GEO_COORDS'
export const EPOSTALCODE = 'ERROR_INVALID_POSTAL_CODE'
