import { getOneLevel, getTwoLevels } from '../transforms/addressFieldsOptions'
import { POSTAL_CODE } from '../constants'

const countryData = {
  'Andaman and Nicobar Islands': ['Port Blair'],
  'Andhra Pradesh': [
    'Adoni',
    'Amaravati',
    'Anantapur',
    'Chandragiri',
    'Chittoor',
    'Dowlaiswaram',
    'Eluru',
    'Guntur',
    'Kadapa',
    'Kakinada',
    'Kurnool',
    'Machilipatnam',
    'Nagarjunakoṇḍa',
    'Rajahmundry',
    'Srikakulam',
    'Tirupati',
    'Vijayawada',
    'Visakhapatnam',
    'Vizianagaram',
    'Yemmiganur',
  ],
  'Arunachal Pradesh': ['Itanagar'],
  Assam: [
    'Dhuburi',
    'Dibrugarh',
    'Dispur',
    'Guwahati',
    'Jorhat',
    'Nagaon',
    'Sivasagar',
    'Silchar',
    'Tezpur',
    'Tinsukia',
  ],
  Bihar: [
    'Ara',
    'Barauni',
    'Begusarai',
    'Bettiah',
    'Bhagalpur',
    'Bihar Sharif',
    'Bodh Gaya',
    'Buxar',
    'Chapra',
    'Darbhanga',
    'Dehri',
    'Dinapur Nizamat',
    'Gaya',
    'Hajipur',
    'Jamalpur',
    'Katihar',
    'Madhubani',
    'Motihari',
    'Munger',
    'Muzaffarpur',
    'Patna',
    'Purnia',
    'Pusa',
    'Saharsa',
    'Samastipur',
    'Sasaram',
    'Sitamarhi',
    'Siwan',
  ],
  Chandigarh: ['Chandigarh'],
  Chhattisgarh: [
    'Ambikapur',
    'Bhilai',
    'Bilaspur',
    'Dhamtari',
    'Durg',
    'Jagdalpur',
    'Raipur',
    'Rajnandgaon',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
  Delhi: ['Delhi', 'New Delhi'],
  Goa: ['Madgaon', 'Panaji'],
  Gujarat: [
    'Ahmadabad',
    'Amreli',
    'Bharuch',
    'Bhavnagar',
    'Bhuj',
    'Dwarka',
    'Gandhinagar',
    'Godhra',
    'Jamnagar',
    'Junagadh',
    'Kandla',
    'Khambhat',
    'Kheda',
    'Mahesana',
    'Morbi',
    'Nadiad',
    'Navsari',
    'Okha',
    'Palanpur',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Surat',
    'Surendranagar',
    'Valsad',
    'Veraval',
  ],
  Haryana: [
    'Ambala',
    'Bhiwani',
    'Chandigarh',
    'Faridabad',
    'Firozpur Jhirka',
    'Gurugram',
    'Hansi',
    'Hisar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Panipat',
    'Pehowa',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Dalhousie',
    'Dharmshala',
    'Hamirpur',
    'Kangra',
    'Kullu',
    'Mandi',
    'Nahan',
    'Shimla',
    'Una',
  ],
  'Jammu and Kashmir': [
    'Anantnag',
    'Baramula',
    'Doda',
    'Gulmarg',
    'Jammu',
    'Kathua',
    'Punch',
    'Rajouri',
    'Srinagar',
    'Udhampur',
  ],
  Jharkhand: [
    'Bokaro',
    'Chaibasa',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'Giridih',
    'Hazaribag',
    'Jamshedpur',
    'Jharia',
    'Rajmahal',
    'Ranchi',
    'Saraikela',
  ],
  Karnataka: [
    'Badami',
    'Ballari',
    'Bengaluru',
    'Belagavi',
    'Bhadravati',
    'Bidar',
    'Chikkamagaluru',
    'Chitradurga',
    'Davangere',
    'Halebid',
    'Hassan',
    'Hubballi-Dharwad',
    'Kalaburagi',
    'Kolar',
    'Madikeri',
    'Mandya',
    'Mangaluru',
    'Mysuru',
    'Raichur',
    'Shivamogga',
    'Shravanabelagola',
    'Shrirangapattana',
    'Tumakuru',
    'Vijayapura',
  ],
  Kerala: [
    'Alappuzha',
    'Vatakara',
    'Idukki',
    'Kannur',
    'Kochi',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Mattancheri',
    'Palakkad',
    'Thalassery',
    'Thiruvananthapuram',
    'Thrissur',
  ],
  Ladakh: ['Kargil', 'Leh'],
  'Madhya Pradesh': [
    'Balaghat',
    'Barwani',
    'Betul',
    'Bharhut',
    'Bhind',
    'Bhojpur',
    'Bhopal',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dr. Ambedkar Nagar (Mhow)',
    'Guna',
    'Gwalior',
    'Hoshangabad',
    'Indore',
    'Itarsi',
    'Jabalpur',
    'Jhabua',
    'Khajuraho',
    'Khandwa',
    'Khargone',
    'Maheshwar',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Murwara',
    'Narsimhapur',
    'Narsinghgarh',
    'Narwar',
    'Neemuch',
    'Nowgong',
    'Orchha',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Sarangpur',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Ujjain',
    'Vidisha',
  ],
  Maharashtra: [
    'Ahmadnagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Bhandara',
    'Bhusawal',
    'Bid',
    'Buldhana',
    'Chandrapur',
    'Daulatabad',
    'Dhule',
    'Jalgaon',
    'Kalyan',
    'Karli',
    'Kolhapur',
    'Mahabaleshwar',
    'Malegaon',
    'Matheran',
    'Mumbai',
    'Nagpur',
    'Nanded',
    'Nashik',
    'Osmanabad',
    'Pandharpur',
    'Parbhani',
    'Pune',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sevagram',
    'Solapur',
    'Thane',
    'Ulhasnagar',
    'Vasai-Virar',
    'Wardha',
    'Yavatmal',
  ],
  Manipur: ['Imphal'],
  Meghalaya: ['Cherrapunji', 'Shillong'],
  Mizoram: ['Aizawl', 'Lunglei'],
  Nagaland: ['Kohima', 'Mon', 'Phek', 'Wokha', 'Zunheboto'],
  Odisha: [
    'Balangir',
    'Baleshwar',
    'Baripada',
    'Bhubaneshwar',
    'Brahmapur',
    'Cuttack',
    'Dhenkanal',
    'Kendujhar',
    'Konark',
    'Koraput',
    'Paradip',
    'Phulabani',
    'Puri',
    'Sambalpur',
    'Udayagiri',
  ],
  Puducherry: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  Punjab: [
    'Amritsar',
    'Batala',
    'Chandigarh',
    'Faridkot',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Nabha',
    'Patiala',
    'Rupnagar',
    'Sangrur',
  ],
  Rajasthan: [
    'Abu',
    'Ajmer',
    'Alwar',
    'Amer',
    'Barmer',
    'Beawar',
    'Bharatpur',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Chittaurgarh',
    'Churu',
    'Dhaulpur',
    'Dungarpur',
    'Ganganagar',
    'Hanumangarh',
    'Jaipur',
    'Jaisalmer',
    'Jalor',
    'Jhalawar',
    'Jhunjhunu',
    'Jodhpur',
    'Kishangarh',
    'Kota',
    'Merta',
    'Nagaur',
    'Nathdwara',
    'Pali',
    'Phalodi',
    'Pushkar',
    'Sawai Madhopur',
    'Shahpura',
    'Sikar',
    'Sirohi',
    'Tonk',
    'Udaipur',
  ],
  Sikkim: ['Gangtok', 'Gyalshing', 'Lachung', 'Mangan'],
  'Tamil Nadu': [
    'Arcot',
    'Chengalpattu',
    'Chennai',
    'Chidambaram',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kanchipuram',
    'Kanniyakumari',
    'Kodaikanal',
    'Kumbakonam',
    'Madurai',
    'Mamallapuram',
    'Nagappattinam',
    'Nagercoil',
    'Palayamkottai',
    'Pudukkottai',
    'Rajapalayam',
    'Ramanathapuram',
    'Salem',
    'Thanjavur',
    'Tiruchchirappalli',
    'Tirunelveli',
    'Tiruppur',
    'Thoothukudi',
    'Udhagamandalam',
    'Vellore',
  ],
  Telangana: [
    'Hyderabad',
    'Karimnagar',
    'Khammam',
    'Mahbubnagar',
    'Nizamabad',
    'Sangareddi',
    'Warangal',
  ],
  Tripura: ['Agartala'],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Amroha',
    'Ayodhya',
    'Azamgarh',
    'Bahraich',
    'Ballia',
    'Banda',
    'Bara Banki',
    'Bareilly',
    'Basti',
    'Bijnor',
    'Bithur',
    'Budaun',
    'Bulandshahr',
    'Deoria',
    'Etah',
    'Etawah',
    'Faizabad',
    'Farrukhabad-cum-Fatehgarh',
    'Fatehpur',
    'Fatehpur Sikri',
    'Ghaziabad',
    'Ghazipur',
    'Gonda',
    'Gorakhpur',
    'Hamirpur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur',
    'Lakhimpur',
    'Lalitpur',
    'Lucknow',
    'Mainpuri',
    'Mathura',
    'Meerut',
    'Mirzapur-Vindhyachal',
    'Moradabad',
    'Muzaffarnagar',
    'Partapgarh',
    'Pilibhit',
    'Prayagraj',
    'Rae Bareli',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Shahjahanpur',
    'Sitapur',
    'Sultanpur',
    'Tehri',
    'Varanasi',
  ],
  Uttarakhand: [
    'Almora',
    'Dehra Dun',
    'Haridwar',
    'Mussoorie',
    'Nainital',
    'Pithoragarh',
  ],
  'West Bengal': [
    'Alipore',
    'Alipur Duar',
    'Asansol',
    'Baharampur',
    'Bally',
    'Balurghat',
    'Bankura',
    'Baranagar',
    'Barasat',
    'Barrackpore',
    'Basirhat',
    'Bhatpara',
    'Bishnupur',
    'Budge Budge',
    'Burdwan',
    'Chandernagore',
    'Darjeeling',
    'Diamond Harbour',
    'Dum Dum',
    'Durgapur',
    'Halisahar',
    'Haora',
    'Hugli',
    'Ingraj Bazar',
    'Jalpaiguri',
    'Kalimpong',
    'Kamarhati',
    'Kanchrapara',
    'Kharagpur',
    'Cooch Behar',
    'Kolkata',
    'Krishnanagar',
    'Malda',
    'Midnapore',
    'Murshidabad',
    'Nabadwip',
    'Palashi',
    'Panihati',
    'Purulia',
    'Raiganj',
    'Santipur',
    'Shantiniketan',
    'Shrirampur',
    'Siliguri',
    'Siuri',
    'Tamluk',
    'Titagarh',
  ],
}

export default {
  country: 'IND',
  abbr: 'IN',
  postalCodeFrom: POSTAL_CODE,
  fields: [
    {
      hidden: true,
      name: 'country',
      maxLength: 100,
      label: 'country',
      size: 'medium',
    },
    {
      name: 'postalCode',
      maxLength: 50,
      required: true,
      label: 'postalCode',
      size: 'small',
      regex: '^[1-9][0-9]{5}$',
      autoComplete: 'nope',
      postalCodeAPI: false,
    },
    {
      name: 'street',
      label: 'addressLine1',
      required: true,
      size: 'xlarge',
    },
    {
      hidden: true,
      name: 'number',
      maxLength: 750,
      label: 'number',
      size: 'small',
      autoComplete: 'nope',
    },
    {
      name: 'complement',
      maxLength: 750,
      label: 'addressLine2',
      size: 'xlarge',
    },
    {
      hidden: true,
      name: 'reference',
      maxLength: 750,
      label: 'reference',
      size: 'xlarge',
    },
    {
      hidden: true,
      name: 'neighborhood',
      maxLength: 100,
      label: 'neighborhood',
      size: 'large',
    },
    {
      name: 'state',
      maxLength: 100,
      label: 'state',
      required: true,
      size: 'large',
      level: 1,
      options: getOneLevel(countryData),
    },
    {
      name: 'city',
      maxLength: 100,
      label: 'city',
      required: true,
      size: 'large',
      level: 2,
      basedOn: 'state',
      optionsMap: getTwoLevels(countryData),
    },
    {
      name: 'receiverName',
      elementName: 'receiver',
      maxLength: 750,
      label: 'receiverName',
      size: 'xlarge',
      required: true,
    },
  ],
  geolocation: {
    postalCode: {
      valueIn: 'long_name',
      types: ['postal_code'],
      required: false,
    },

    number: {
      valueIn: 'long_name',
      types: ['street_number'],
      required: false,
      notApplicable: true,
    },

    street: { valueIn: 'long_name', types: ['route'] },

    neighborhood: {
      valueIn: 'long_name',
      types: [
        'neighborhood',
        'sublocality_level_1',
        'sublocality_level_2',
        'sublocality_level_3',
        'sublocality_level_4',
        'sublocality_level_5',
      ],
    },

    state: {
      valueIn: 'long_name',
      types: ['administrative_area_level_1'],
    },

    city: {
      valueIn: 'long_name',
      types: ['administrative_area_level_2', 'locality'],
    },

    receiverName: {
      required: true,
    },
  },
  summary: [
    [
      {
        name: 'street',
      },
      {
        delimiter: ' ',
        name: 'number',
      },
      {
        delimiter: ', ',
        name: 'complement',
      },
    ],
    [
      {
        name: 'neighborhood',
        delimiterAfter: ' - ',
      },
      {
        name: 'city',
      },
      {
        delimiter: ' - ',
        name: 'state',
      },
    ],
    [
      {
        name: 'postalCode',
      },
    ],
  ],
}
