import { getOneLevel, getTwoLevels } from '../transforms/addressFieldsOptions'

import { POSTAL_CODE } from '../constants'

import type { PostalCodeRules } from '../types/rules'

const countryData = {
  Artigas: [
    'Artigas',
    'Baltasar Brum',
    'Bella Unión',
    'Bernabe Rivera',
    'Cainsa',
    'Cainza Campo',
    'Cainza Campo 3',
    'Calnu',
    'Calpica Itacumbú',
    'Camano',
    'Catalan Grande',
    'Catalan Volcan',
    'Cerrito',
    'Cerro Ejido',
    'Cerro San Eugenio',
    'Cerro Signorelli',
    'Chiflero',
    'Colonia Aparicio Saravia',
    'Colonia Espana',
    'Colonia Estrella',
    'Colonia Jose Artigas',
    'Colonia Palma',
    'Colonia Pintado',
    'Colonia Vinar',
    'Coronado',
    'Cota 205',
    'Cuareim',
    'Cuaró',
    'Diego Lamas',
    'Estiba',
    'Fagundez',
    'Franquia',
    'Guyubira',
    'Javier De Viana',
    'La Bolsa',
    'Las Piedras',
    'Lenguazo',
    'Limite Contestado',
    'Meneses',
    'Menezes',
    'Mones Quintela',
    'Paguero',
    'Palma Sola',
    'Paraje Diego Lamas',
    'Paredon',
    'Pasaje Paso Campamento',
    'Paso Campamento',
    'Paso De La Cruz',
    'Paso De Leon',
    'Paso De Ramos',
    'Paso Farias',
    'Patitas',
    'Piedra Pintada',
    'Pintadito',
    'Pintado',
    'Pintado Grande',
    'Pje. Paso Campamento',
    'Port. De Hierro Y Campodonico',
    'Porton De Hierro Y Campodonico',
    'Portones De Hierro Y Campodonico',
    'Pueblo Sequeira',
    'Rincon De Pacheco',
    'Sarandi De Cuaro',
    'Sarandi De Yacuy',
    'Sequeira',
    'Tamandua',
    'Taruman',
    'Tomas Gomensoro',
    'Topador',
    'Zanja Aruera',
  ],
  Canelones: [
    'Acapulco',
    'Aeropuerto',
    'Aeropuerto Internacional De Carrasco',
    'Aguas Corrientes',
    'Altos De La Tahona',
    'Araminda',
    'Arenal',
    'Argentino',
    'Atlántida',
    'B.H.U.',
    'Balneario Argentino',
    'Balneario San Luis',
    'Banco Hipotecario Uruguay',
    'Barra De Carrasco',
    'Barra De La Pedrera',
    'Barra Del Tala',
    'Barrancas Coloradas',
    'Barrio Artigas',
    'Barrio Benzo',
    'Barrio Copola',
    'Barrio Del Libertador',
    'Barrio La Lucha',
    'Barrio Los Panoramas',
    'Barrio Monterrey',
    'Barrio Obrero',
    'Barrio Pretti',
    'Barrio Remanso',
    'Barrio San Cristobal',
    'Barrio Santa Rita',
    'Barrio Traverso',
    'Barrio Villa Murcia',
    'Barros Blancos',
    'Bañado De Medina',
    'Bañados de Carrasco',
    'Bello Horizonte',
    'Biarritz',
    'Blanco',
    'Bolívar',
    'Camino De La Cadena',
    'Camino Dodera',
    'Camino Lloveras',
    'Campo Militar',
    'Canada Cardozo',
    'Canada De Montano',
    'Canada Grande',
    'Canada Prudencio',
    'Canelon Chico',
    'Canelon Chico Al Centro',
    'Canelon Chico De Progreso',
    'Canelon Grande',
    'Canelon Grande De Pacheco',
    'Canelon Grande Norte',
    'Canelones',
    'Canelón Grande Represa',
    'Capilla De Cella',
    'Capitan Juan Antonio Artigas',
    'Carmel',
    'Carrasco Del Sauce',
    'Casarino',
    'Castellanos',
    'Cerrillos',
    'Cerrillos Al Oeste',
    'Cerrillos Al Sur',
    'Chamizo',
    'City Golf',
    'Ciudad De La Costa',
    'Cochengo',
    'Colinas De Carrasco',
    'Colinas De Solymar',
    'Colonia Lamas',
    'Colonia Nicolich',
    'Colonia Treinta Y Tres Orientales',
    'Colorado Chico',
    'Colorado Y Brujas',
    'Costa Azul',
    'Costa De Pando',
    'Costa De Pando Olmos',
    'Costa De Pando San Bautista',
    'Costa De Pando San Jacinto',
    'Costa Del Pantanoso',
    'Costa Del Sauce',
    'Costa Del Tala Este',
    'Costa Del Tala Norte',
    'Costa Y Guillamon',
    'Costas De Pedernal',
    'Costas De Santa Lucia',
    'Costas De Solis',
    'Costas Del Colorado',
    'Costas Del Colorado Este',
    'Costas Del Tala',
    'Cruz De Los Caminos',
    'Cuchilla Alta',
    'Cuchilla Alta Y El Galeon',
    'Cuchilla Cabo De Hornos',
    'Cuchilla De Machin',
    'Cuchilla De Rocha',
    'Cuchilla De Sierra',
    'Cuchilla De Zeballos',
    'Cuchilla Verde',
    'Cueva Del Tigre',
    'Cumbres De Carrasco',
    'Doctor Francisco Soca',
    'Dr. Francisco Soca',
    'Echevarria',
    'El Bosque',
    'El Bosque De Lagomar',
    'El Bosque De Solymar',
    'El Colorado',
    'El Colorado De Migues',
    'El Colorado San Bautista',
    'El Cuadro',
    'El Dorado',
    'El Fortín De Santa Rosa',
    'El Galeon',
    'El Pinar',
    'Empalme Dogliotti',
    'Empalme Nicolich',
    'Empalme Olmos',
    'Empalme Sauce',
    'Esquina Gonzalez',
    'Est. Atlántida',
    'Estacion Atlantida',
    'Estacion La Floresta',
    'Estacion Piedras De Afilar',
    'Estación Migues',
    'Estación Pedrera',
    'Estación Tapia',
    'Estanque De Pando',
    'Feliciano',
    'Fortin De Santa Rosa',
    'Fracc Sobre Ruta 74',
    'Fracc. Camino Maldonado',
    'Fracc. Cno. Andaluz Y R.8',
    'Fracc. Cno. Andaluz Y R.84',
    'Fracc. Progreso',
    'Fraccionamiento Camino Andaluz Y Ruta 84',
    'Fraccionamiento Progreso',
    'Fray Marcos',
    'General Liber Seregni',
    'Guazuvirá',
    'Guazuvirá Nuevo',
    'Haras Del Lago',
    'Instituto Adventista',
    'Jardines De Pando',
    'Jaureguiberry',
    'Joanicó',
    'Joaquín Suárez',
    'Juan Antonio Artigas',
    'Juanico',
    'La Asuncion',
    'La Chinchilla',
    'La Escobilla',
    'La Floresta',
    'La Montañesa',
    'La Palmita',
    'La Paloma',
    'La Paz',
    'La Tahona',
    'La Totora',
    'La Tuna',
    'Lago Jardin Del Bosque',
    'Lagomar',
    'Las Brujas',
    'Las Higueritas',
    'Las Piedras',
    'Las Ranas',
    'Las Toscas',
    'Las Vegas',
    'Las Violetas',
    'Lomas De Carrasco',
    'Lomas De Solymar',
    'Lomas De Toledo',
    'Los Ceibos',
    'Los Cerrillos',
    'Los Hornos',
    'Los Titanes',
    'Macana',
    'Margat',
    'Marindia',
    'Mata Siete',
    'Mataojo',
    'Melgarejo',
    'Migues',
    'Mirador De La Tahona',
    'Monaco De Carrasco',
    'Montes',
    'Montes De Solymar',
    'Murialdo',
    'Médanos De Solymar',
    'Nataly',
    'Neptunia',
    'Nutrias',
    'Olmos',
    'Pando',
    'Pantanoso',
    'Pantanoso Del Sauce',
    'Parada Cabrera',
    'Parador Tajes',
    'Paraje San Juan',
    'Parque Carrasco',
    'Parque De Solymar',
    'Parque Del Plata',
    'Parque Miramar',
    'Paso Arbelo',
    'Paso Carrasco',
    'Paso De Carrasco',
    'Paso De Cuello',
    'Paso De La Cadena',
    'Paso De La Paloma',
    'Paso De La Salamanca',
    'Paso De Las Toscas',
    'Paso De Los Alamos',
    'Paso De Los Difuntos',
    'Paso De Los Francos',
    'Paso De Pache',
    'Paso Del Bote',
    'Paso Del Colorado',
    'Paso Del Medio',
    'Paso Del Sordo',
    'Paso Espinosa',
    'Paso Palomeque',
    'Paso Rivero De Vejigas',
    'Pedernal',
    'Pedernal Chico',
    'Pedernal Grande',
    'Piedra Del Toro',
    'Piedra Sola',
    'Piedras De Afilar',
    'Piedritas',
    'Piedritas De Suarez',
    'Pinamar',
    'Pinamar - Pinepark',
    'Pinamar Y Pinepark',
    'Pinares De Solymar',
    'Pine Park',
    'Ponce Mata Siete',
    'Poquitos',
    'Progreso',
    'Pueblo Castellanos',
    'Pueblo Suizo',
    'Puente De Brujas',
    'Puntas De Brujas',
    'Puntas De Canada Cardozo',
    'Puntas De Canada Grande',
    'Puntas De Canelon Chico',
    'Puntas De Cochengo',
    'Puntas De Las Violetas',
    'Puntas De Mata Siete',
    'Puntas De Pantanoso',
    'Puntas De Pantanoso Este',
    'Puntas De Pedrera',
    'Puntas De Toledo',
    'Puntas De Vejigas',
    'Puntas Del Arenal',
    'Quinta Los Horneros',
    'Quintas Del Bosque',
    'Rancherios De Ponce',
    'Rincon De Carrasco',
    'Rincon De Pando',
    'Rincon De Portezuelo',
    'Rincon De Velazquez',
    'Rincon De Vidal',
    'Rincon Del Colorado',
    'Rincon Del Conde',
    'Rincon Del Gigante',
    'Salinas',
    'Salinas Sur',
    'San Andres',
    'San Antonio',
    'San Bautista',
    'San Cristobal',
    'San Jacinto',
    'San José De Carrasco',
    'San Luis',
    'San Pedro',
    'San Ramón',
    'Santa Ana',
    'Santa Lucía',
    'Santa Lucía Del Este',
    'Santa Rosa',
    'Santa Teresita',
    'Santos Lugares',
    'Sarandi De Migues',
    'Sauce',
    'Sauce De Solis',
    'Sauce Solo',
    'Sauce Solo De Migues',
    'Sauce Solo De Montes',
    'Seis Hermanos',
    'Shangrila',
    'Sierra del Mar',
    'Soca',
    'Sofia Santos',
    'Solis Chico',
    'Solis Chico De Migues',
    'Solymar',
    'Sosa Diaz',
    'Suarez',
    'Tala',
    'Talita',
    'Toledo',
    'Toledo Chico',
    'Totoral',
    'Totoral Del Sauce',
    'Vejigas',
    'Vejigas De San Ramon',
    'Vejigas De Tala',
    'Viejo Molino San Bernardo',
    'Villa Aeroparque',
    'Villa Arejo',
    'Villa Argentina',
    'Villa Crespo',
    'Villa Crespo Y San Andres',
    'Villa Del Mar',
    'Villa El Tato',
    'Villa Encantada',
    'Villa Felicidad',
    'Villa Foresti',
    'Villa Fortuna',
    'Villa Gabi',
    'Villa Hadita',
    'Villa Huertos De Toledo',
    'Villa Juana',
    'Villa Juanita',
    'Villa Los Alpes',
    'Villa Marina',
    'Villa Molfino',
    'Villa Nueva',
    'Villa Paz S.A.',
    'Villa Paz Sociedad Anonima',
    'Villa Prados De Toledo',
    'Villa San Cono',
    'Villa San Felipe',
    'Villa San Jose',
    'Villa Valverde',
    'Vina Del Mar',
    'Vista Linda',
  ],
  'Cerro Largo': [
    'Aceguá',
    'Aguirre',
    'Amarillo',
    'Arachania',
    'Arbolito',
    'Arevalo',
    'Arroyo Malo',
    'Arrozal Cesarone',
    'Arrozal Rosales',
    'Asperezas',
    'Banado De Las Pajas',
    'Barra Del Sauce',
    'Barra Del Tacuari',
    'Barrio La Vinchuca',
    'Barrio Lopez Benitez',
    'Bañado De Medina',
    'Berachi',
    'Buena Vista',
    'Calera De Recalde',
    'Campamento',
    'Canada Brava',
    'Canada De Santos',
    'Canada Grande',
    'Canada Sarandi',
    'Canitas',
    'Casa De Las Cronicas',
    'Caserio Las Canas',
    'Cementerio',
    'Centurion',
    'Cerro De Las Cuentas',
    'Chacras De Melo',
    'Coimbra',
    'Colonia Ceres',
    'Colonia Maria Teresa',
    'Colonia Orozco',
    'Conventos',
    'Corral De Piedra',
    'Cruz De Piedra',
    'Cuchilla Cambota',
    'Cuchilla De Melo',
    'Cuchilla Del Carmen',
    'Cuchilla Del Paraiso',
    'Cuchilla Peralta',
    'Duraznero',
    'Escuela De Agronomia',
    'Esperanza',
    'Falda De Sierra De Los Ri',
    'Falda De Sierra De Los Rios',
    'Fraile Muerto',
    'Ganen',
    'Garao',
    'Granja De Acegua',
    'Granja Pallero',
    'Guazunambi',
    'Hipodromo',
    'Infiernillo',
    'Isidoro Noblía',
    'La Coronilla',
    'La Gloria',
    'La Micaela',
    'La Mina',
    'La Pedrera',
    'Lago Merín',
    'Laguna Del Junco',
    'Laguna Merin',
    'Las Limas',
    'Los Cerros',
    'Mangrullo',
    'Maria Isabel',
    'Mazangano',
    'Melo',
    'Minuano De Acegua',
    'Misterio',
    'Montecito',
    'Nando',
    'Nangapire',
    'Panteon',
    'Paso De La Cruz',
    'Paso De Las Tropas',
    'Paso De Las Yeguas',
    'Paso De Los Carros',
    'Paso Melo',
    'Paso Pereira',
    'Peñarol',
    'Picada De Maya',
    'Picada De Salome',
    'Piedra Alta',
    'Pineiro',
    'Plácido Rosas',
    'Poblado Uruguay',
    'Presidente Doctor Getulio',
    'Presidente Doctor Getulio Vargas',
    'Puente Negro',
    'Puntas De Amarillo',
    'Puntas De La Mina',
    'Puntas De Molles',
    'Puntas De Palleros',
    'Puntas De Tacuari',
    'Puntas Del Sauce',
    'Quebracho',
    'Ramon Trigo',
    'Rincon De Contreras',
    'Rincon De La Urbana',
    'Rincon De Los Coroneles',
    'Rincon De Los Olivera',
    'Rincon De Paiva',
    'Rincon De Py',
    'Rincon De Suarez',
    'Rincon De Tacuari',
    'Rodriguez',
    'Río Branco',
    'Saldanas',
    'San Diego',
    'San Servando',
    'Sanchez',
    'Santa Teresa',
    'Sarandi De Acegua',
    'Sarandi De Barcelo',
    'Sarandi De Yaguaron',
    'Sauce De Conventos',
    'Soto Goro',
    'Toledo',
    'Tres Boliches',
    'Tres Islas',
    'Tupambaé',
    'Uruguay',
    'Villa Vinoles',
    'Wenceslao Silvera',
  ],
  Colonia: [
    'Agraciada',
    'Arrivillaga',
    'Artilleros',
    'Barker',
    'Barker Norte',
    'Barrancas Coloradas',
    'Barrio Mendana',
    'Barrio Olimpico',
    'Belgrano Norte',
    'Belgrano Sur',
    'Blanca Arena',
    'Boca Del Rosario',
    'Boca Del Rosario Oeste',
    'Bonjour',
    'Brisas Del Plata',
    'Buena Hora',
    'Campamento Artigas',
    'Campana',
    'Carmelo',
    'Caserio El Cerro',
    'Cerro Carmelo',
    'Cerro De Las Armas',
    'Cerros De San Juan',
    'Cerros Negros',
    'Chico Torino',
    'Colonia',
    'Colonia Arrue',
    'Colonia Cosmopolita',
    'Colonia Del Sacramento',
    'Colonia Espanola Km. 109',
    'Colonia Española',
    'Colonia Estrella',
    'Colonia Miguelete',
    'Colonia Peirano',
    'Colonia Quevedo',
    'Colonia Sarandi',
    'Colonia Suiza',
    'Colonia Talice',
    'Colonia Valdense',
    'Conchillas',
    'Concordia',
    'Costa De Colla Al Este',
    'Costa De Rosario',
    'Costa De Tarariras',
    'Costa De Vacas',
    'Costa Del Navarro',
    'Costas De Juan Gonzalez',
    'Costas De Polonia',
    'Costas De San Juan',
    'Cufré',
    'Curupi',
    'El Banado',
    'El Cano',
    'El Cerro',
    'El Chileno',
    'El Cuadro',
    'El Ensueno',
    'El Faro',
    'El General',
    'El Quinton',
    'El Semillero',
    'Estacion Estanzuela',
    'Estacion Experimental "La E',
    'Estacion Experimental "La Estanzuela"',
    'Estacion Experimental La Estanzuela',
    'Estancia Anchorena',
    'Florencio Sánchez',
    'Fomento',
    'Gil',
    'Juan Carlos Caseros',
    'Juan Gonzalez',
    'Juan Jackson',
    'Juan L. Lacaze',
    'Juan Lacaze',
    'La Estanzuela',
    'La Horqueta',
    'La Paz',
    'La Sierra',
    'Laguna De Los Patos',
    'Las Chispas',
    'Las Flores',
    'Lomas De Carmelo',
    'Los Pinos',
    'Manantiales',
    'Martin Chico',
    'Martin Chico De Conchillas',
    'Media Agua',
    'Miguelete',
    'Miguelete De Conchillas',
    'Minas De Narancio',
    'Minuano',
    'Minuano Y Sauce',
    'Molles De Miguelete',
    'Nueva Helvecia',
    'Nueva Palmira',
    'Ombúes De Lavalle',
    'Paraje Minuano',
    'Paso Antolin',
    'Paso Birriel',
    'Paso De La Quinta',
    'Paso Hospital',
    'Paso Hospital Manantiales',
    'Paso Morlan',
    'Paso Quicho',
    'Pastoreo',
    'Picada De Benitez',
    'Piedra Chata',
    'Piedra De Los Indios',
    'Piedras Blancas',
    'Playa Azul',
    'Playa Britopolis',
    'Playa Fomento',
    'Playa Parant',
    'Polancos',
    'Puerto Concordia',
    'Puerto Ingles',
    'Puerto Platero',
    'Puerto Rosario',
    'Punta Francesa',
    'Puntas De Juan Gonzalez',
    'Puntas De Melo',
    'Puntas De San Juan',
    'Puntas De San Pedro',
    'Puntas Del Riachuelo',
    'Puntas Del Rosario',
    'Puntas Del Sauce',
    'Quinton',
    'Radial Hernandez',
    'Radial Rosario',
    'Real De Vera',
    'Reducto',
    'Resguardo Cufre',
    'Riachuelo',
    'Rincon Del Rey',
    'Rosario',
    'Rosario Y Colla',
    'San Juan',
    'San Luis',
    'San Luis De Tarariras',
    'San Luis Sanchez',
    'San Pedro',
    'San Pedro De Arriba',
    'San Pedro Norte',
    'San Roque',
    'Santa Ana',
    'Santa Regina',
    'Santa Rosa',
    'Sarandi Campana',
    'Tarariras',
    'Terminal',
    'Tomas Bell',
    'Tres Esquinas',
    'Valdenese',
    'Viboras',
    'Viboras Y Vacas',
    'Villa Pancha',
    'Zagarzazu',
    'Zunin',
  ],
  Durazno: [
    'Abella',
    'Aguas Buenas',
    'Arroyo De Los Perros',
    'Barrancas Coloradas',
    'Barrio Duran',
    'Batovi',
    'Baygorria',
    'Blanquillo',
    'Blanquillo Al Oeste',
    'Caballero',
    'Capilla De Farruco',
    'Carlos Reyles',
    'Ceibal',
    'Centenario',
    'Cerrezuelo',
    'Cerro Chato',
    'Cerro Convento',
    'Chacras De Durazno',
    'Chileno',
    'Chileno Chico',
    'Chileno Grande (Aguero)',
    'Costa De Cuadra',
    'Cuchilla De Ramirez',
    'Cuchilla Del Rincon',
    'De Dios',
    'Durazno',
    'Elias Regules',
    'Estacion Chileno',
    'Feliciano',
    'Fonseca',
    'Higueras De Carpinteria',
    'La Alegria',
    'La Mazamorra',
    'La Paloma',
    'Las Acacias',
    'Las Canas',
    'Las Palmas',
    'Las Tunas',
    'Los Agregados',
    'Los Tapes',
    'Maestre Campo',
    'Malbajar Este',
    'Malbajar Oeste',
    'Maria Cejas',
    'Mariscala',
    'Mariscala Del Carmen',
    'Molles Chico',
    'Molles De Quinteros',
    'Mourino',
    'Municipio De Durazno',
    'Ombues De Oribe',
    'Palmar De Porrua',
    'Parada Sur',
    'Parish',
    'Paso De Aguirre',
    'Paso De Castro',
    'Paso Del Medio Las Palmas',
    'Paso Ramirez',
    'Paso Real De Carpinteria',
    'Paso Tejera',
    'Pueblo Centenario',
    'Pueblo De Alvarez',
    'Puglia',
    'Puntas De Carpinteria',
    'Puntas De Herrera',
    'Puntas De Malbajar',
    'Rincon De Cuadra',
    'Rincon De Los Tapes',
    'Rolon',
    'Rossell Y Rius',
    'Salinas',
    'Salinas Chico',
    'San Jorge',
    'San Jose De Las Canas',
    'Sande Chico',
    'Sandu Chico',
    'Santa Bernardina',
    'Sarandi De La China',
    'Sarandi De Rio Negro',
    'Sarandí Del Yí',
    'Sauce De Herrera',
    'Sauce Del Yi',
    'Tala De Mariscala',
    'Tejera',
    'Verdun',
    'Villa Del Carmen',
    'Villasboas',
  ],
  Flores: [
    'Ahogados',
    'Andresito',
    'Arenal Chico',
    'Arenal Grande',
    'Arroyo Malo',
    'Canada Amilivia',
    'Cerro Colorado (No se usa mas)',
    'Chacras',
    'Chacras De Borghi',
    'Colonia Alemana',
    'Costas De San Jose',
    'Costas Del Tala',
    'Cuchilla De Villasboas',
    'El Coronilla',
    'El Totoral',
    'Ferrizo',
    'Ismael Cortinas',
    'Juan Jose Castro',
    'La Alianza',
    'La Casilla',
    'La Cordobesa',
    'La Guardia',
    'Los Puentes',
    'Marincho',
    'Paso De Lugo',
    'Paso Hondo',
    'Pueblo Pintos',
    'Puntas De Chamanga',
    'Puntas De Marincho',
    'Puntas De San Jose',
    'Puntas De Sarandi',
    'Puntas Del Corral De Pied',
    'Puntas Del Corral De Piedra',
    'Puntas Del Sauce',
    'Rincon Del Palacio',
    'San Gregorio De Flores',
    'Santa Adelaida',
    'Sarandi',
    'Talas De Maciel',
    'Trinidad',
    'Villa Pastora',
    'Villasboas',
  ],
  Florida: [
    '25 De Agosto',
    '25 De Mayo',
    'Alejandro Gallinal',
    'Arrayan',
    'Arroyo Chamizo',
    'Arroyo De Los Negros',
    'Arroyo Latorre',
    'Arroyo Monzon',
    'Arroyo Pelado',
    'Arteaga',
    'Barra Molles Del Timote',
    'Barra Sauce De Mansavillagra',
    'Berrondo',
    'Calleri',
    'Candil',
    'Capilla Del Sauce',
    'Cardal',
    'Caserio La Fundacion',
    'Casupá',
    'Cerro Chato',
    'Cerro Colorado',
    'Cerro De La Macana',
    'Cerros De Florida',
    'Chacras De Florida',
    'Chacras Del Pintado',
    'Chamizo',
    'Chamizo Chico',
    'Chilcas',
    'Chingolas',
    'Colonia Sanchez',
    'Colonia Treinta Y Tres Or',
    'Colonia Treinta Y Tres Orientales',
    'Corral De Piedra',
    'Costa De Arias',
    'Costa De Illescas',
    'Costa De La Cruz',
    'Costa De Parana',
    'Costa Del Tala',
    'Costas De Arias',
    'Costas De Chamizo',
    'Costas De Chamizo Grande',
    'Costas De Maciel',
    'Costas De Santa Lucia Chi',
    'Costas De Santa Lucia Chico',
    'Costas Del Amarillo',
    'Costas Del Pintado',
    'Costas Del Santa Lucia Gr',
    'Costas Del Santa Lucia Grande',
    'Cuchilla Santo Domingo',
    'Dr. Alejandro Gallinal',
    'Estacion Capilla Del Sauc',
    'Estacion Capilla Del Sauce',
    'Ferrer',
    'Florida',
    'Fray Marcos',
    'Goñi',
    'Hernandarias',
    'Illescas',
    'Independencia',
    'José Batlle Y Ordóñez',
    'Juncal',
    'La Cimbra',
    'La Cruz',
    'La Escobilla',
    'La Macana',
    'La Palma',
    'La Victoria',
    'Las Piedritas',
    'Mansavillagra',
    'Mendoza',
    'Mendoza Chico',
    'Mendoza Grande',
    'Molles Del Pescado',
    'Molles Del Timote',
    'Monte Coral',
    'Nico Pérez',
    'Palermo',
    'Pantanoso De Castro',
    'Paso Calleros',
    'Paso De Los Novillos',
    'Paso Real De Mansavillagr',
    'Paso Real De Mansavillagra',
    'Paso Vela',
    'Piedra Campana',
    'Piedras Coloradas',
    'Pintado',
    'Polanco Del Yí',
    'Pueblo De Los Morochos',
    'Puente De Mendoza',
    'Puntas De Calleros',
    'Puntas De Chamame',
    'Puntas De Chamizo',
    'Puntas De Illescas',
    'Puntas De La Escobilla',
    'Puntas De Maciel',
    'Puntas De Mansavillagra',
    'Puntas De Sarandi',
    'Puntas De Sauce De Maciel',
    'Puntas Del Arroyo Latorre',
    'Reboledo',
    'Rincon De Los Camilos',
    'Rincon De Vignoli',
    'Rincon Sauce Del Yi',
    'San Gabriel',
    'San Geronimo',
    'San Juan',
    'San Pedro De Timote',
    'Santa Clara',
    'Santa Teresa',
    'Sarandí Grande',
    'Sauce De Maciel',
    'Sauce De Villanueva',
    'Sauce Del Yi',
    'Tabare',
    'Tala De Castro',
    'Tala De Maciel',
    'Talita',
    'Tornero',
    'Urioste',
    'Valentines',
    'Veinticinco de Mayo',
    'Vignoli',
    'Villa Hipica',
    'Villa Vieja',
  ],
  Lavalleja: [
    '19 De Junio',
    'Abra De Zabaleta',
    'Aguas Blancas',
    'Alonso',
    'Andreoni',
    'Aramendia',
    'Arequita',
    'Arroyo De Los Patos',
    'Arroyo Del Medio',
    'Azucar',
    'Barra De Los Chanchos',
    'Barrancas',
    'Barriga Negra',
    'Barrio La Coronilla - Anc',
    'Barrio La Coronilla - Ancap',
    'Blanes Viale',
    'Campanero',
    'Canteras Del Verdun',
    'Carnales',
    'Casupa Chico',
    'Casupá',
    'Cerro Pelado',
    'Chamame',
    'Colón',
    'Consejo Del Nino',
    'Costa Del Lenguazo',
    'Costas De Corrales',
    'Costas Del Soldado',
    'El Alto',
    'El Perdido',
    'El Soldado',
    'El Tigre',
    'Espuelitas',
    'Estacion Andreoni',
    'Estacion Ortiz',
    'Estación Solís',
    'Gaetan (Cuchilla De Carba',
    'Gaetan (Cuchilla De Carbajal)',
    'Godoy',
    'Gutierrez',
    'Higueritas',
    'Illescas',
    'José Batlle Y Ordóñez',
    'José Pedro Varela',
    'La Cuchilla',
    'La Plata',
    'Ladrillos',
    'Larrosa',
    'Las Achiras',
    'Los Ceibos',
    'Los Tapes',
    'Manguera Azul',
    'Marco De Los Reyes',
    'Maria Isabel',
    'Mariscala',
    'Marmaraja',
    'Minas',
    'Molles De Aigua',
    'Molles De Canada Grande',
    'Molles Del Sauce',
    'Nico Pérez',
    'Ombues De Bentancor',
    'Ombues De Bentancour',
    'Ortiz',
    'Ortiz Castro',
    'Paso Arbelo',
    'Paso De Los Troncos',
    'Paso De Mesa',
    'Pirarajá',
    'Polanco',
    'Polanco Norte',
    'Polanco Sur',
    'Pororo',
    'Puente De Marmaraja',
    'Puntas De Barriga Negra',
    'Puntas De Los Chanchos',
    'Puntas De Polanco',
    'Puntas De San Francisco',
    'Puntas De Santa Lucia',
    'Puntas De Solis',
    'Puntas De Vejigas',
    'Puntas Del Perdido',
    'Retamosa',
    'Rincon De Cebollati',
    'Rincon De Mariscala',
    'Rincon De Silva',
    'Roldan',
    'San Francisco De Las Sier',
    'San Francisco De Las Sierras',
    'Santa Lucía',
    'Sarandi De Gutierrez',
    'Sauce De Aigua',
    'Sauce De Olimar Chico',
    'Sierras Blancas',
    'Soldado',
    'Solis Grande',
    'Solís',
    'Solís De Mataojo',
    'Tapes Chico',
    'Tapes Grande',
    'Valentines',
    'Valle De Solis',
    'Vejigas',
    'Velázquez',
    'Verdun',
    'Villa Del Rosario',
    'Villa Serrana',
    'Zapicán',
  ],
  Maldonado: [
    'Abayuba',
    'Abra De Castellanos',
    'Abra De Perdomo',
    'Aiguá',
    'Alfaro',
    'Alferez',
    'Altos Del Pinar',
    'Andalucia',
    'Apiario',
    'Arenas De Jose Ignacio',
    'Arroyito De Medina',
    'Artigas',
    'B-9',
    'Balneario Buenos Aires',
    'Balneario Las Flores',
    'Balneario San Francisco',
    'Barra De Portezuelo',
    'Barra Del Sauce',
    'Barrio Hipodromo',
    'Barrio Kennedy',
    'Bella Vista',
    'Biarritz - La Candelaria',
    'Bicentenario',
    'Bonet',
    'Buenos Aires',
    'Burnett',
    'Cachimba Del Rey',
    'California Park',
    'Canteras De Marelli',
    'Carape',
    'Carlos Cal',
    'Cañada Bellaca',
    'Cañada De La Cruz',
    'Centro',
    'Cerro Pelado',
    'Cerros Azules',
    'Chihuahua',
    'Colonia J. Suarez',
    'Colonia Joaquin Suarez',
    'Coronilla',
    'Corte De La Leña',
    'Costas De Jose Ignacio',
    'Cuñetti - Los Olivos',
    'Eden Rock',
    'El Cañon',
    'El Chorro',
    'El Cortijo',
    'El Eden',
    'El Hacha',
    'El Quijote',
    'El Tesoro',
    'El Vigia',
    'Esterel',
    'Faro Jose Ignacio',
    'Faro Jose Ignacio Norte',
    'Fernandez Ismendi',
    'Fossemmale',
    'Garzón',
    'Gerona',
    'Gregorio Aznarez',
    'Guardia Vieja',
    'Helguera',
    'Hipico Burnet',
    'Hipodromo',
    'Icar',
    'Inve',
    'Ipora',
    'Jardin De Los 33',
    'Jardin Scalone',
    'Jardines Pinares',
    'Jaurena',
    'José Ignacio',
    'La Barra',
    'La Capuera',
    'La Falda',
    'La Fortuna',
    'La Juanita',
    'La Sierra',
    'La Sonrisa',
    'Lago De Los Cisnes',
    'Laguna Blanca',
    'Laguna Del Sauce',
    'Las Canas',
    'Las Cooperativas',
    'Las Cumbres',
    'Las Delicias',
    'Las Flores',
    'Las Flores - Estacion',
    'Las Marias',
    'Lausana',
    'Lavalleja',
    'Leonel',
    'Los Aromos',
    'Los Ceibos',
    'Los Ciruelos',
    'Los Corchos',
    'Los Talas',
    'Maldonado',
    'Maldonado - Los Patricios ',
    'Maldonado Nuevo',
    'Maldonado Park',
    'Manantiales',
    'Mataojo',
    'Mazzoni',
    'Miguez',
    'Mirador De La Patria',
    'Miramar',
    'Molles De Garzon',
    'Monaco',
    'Mpal. Kennedy',
    'Mussio',
    'Norte',
    'Nueva Carrara',
    'Nuevo Cantegril',
    'Ocean Park',
    'Odizzio',
    'P. Ballena',
    'P. Coloradas',
    'Pago De La Paja',
    'Pan De Azúcar',
    'Parque Medina',
    'Parque Scalone',
    'Partido Norte',
    'Partido Oeste',
    'Paso De La Cantera',
    'Paso De Los Talas',
    'Perlita',
    'Piedras Del Chileno',
    'Pinares',
    'Pinares - Las Delicias',
    'Piriápolis',
    'Playa Grande',
    'Playa Hermosa',
    'Playa Verde',
    'Portezuelo',
    'Pueblo Eden',
    'Pueblo Obrero',
    'Pueblo Solis',
    'Punta Ballena',
    'Punta Colorada',
    'Punta Del Este',
    'Punta Fria',
    'Punta Negra',
    'Punta Piedras',
    'Puntas De Jose Ignacio',
    'Puntas De La Sierra',
    'Puntas De Mataojo',
    'Puntas De Pan De Azucar',
    'Puntas Del Campanera',
    'Reserva Del Este',
    'Rial',
    'Rincon De Aparicio',
    'Rincon De Los Sosa',
    'Rincon Del Indio',
    'Rivera',
    'Ruta 37 Y 9',
    'Salamanca',
    'San Antonio',
    'San Carlos',
    'San Fernando',
    'San Francisco',
    'San Gabriel',
    'San Juan Del Este',
    'San Martin',
    'San Rafael',
    'San Rafael - El Placer',
    'San Vicente',
    'Santa Monica',
    'Santa Teresita',
    'Sarandi De Aigua',
    'Sarandi Del Mataojo',
    'Sarubbi',
    'Sauce De Aigua',
    'Sauce De Portezuelo',
    'Sausalito',
    'Solís',
    'Tassano',
    'Umerez',
    'Valdivia',
    'Villa Delia',
    'Zanja Del Tigre',
  ],
  Montevideo: [
    'Abayuba',
    'Aguada',
    'Aires Puros',
    'Arroyo Seco',
    'Atahualpa',
    'Barrio Sur',
    'Bañados de Carrasco',
    'Bella Italia',
    'Belvedere',
    'Brazo Oriental',
    'Buceo',
    'Capurro',
    'Capurro Bella Vista',
    'Carrasco',
    'Carrasco Norte',
    'Casabo',
    'Casabo Pajas Blancas',
    'Casavalle',
    'Castro',
    'Castro Castellanos',
    'Cementerio del Norte',
    'Centro',
    'Cerrito',
    'Cerrito de la Victoria',
    'Cerro',
    'Chacarita',
    'Ciudad Vieja',
    'Colon Centro y Noroeste',
    'Colon Sureste Abayuba',
    'Colón',
    'Conciliacion',
    'Cordon',
    'Cuchilla Pereira',
    'Flor de Maroñas',
    'Goes',
    'Ituzaingó',
    'Jacinto Vera',
    'Jardines Del Hipodromo',
    'Jardines Hipódromo',
    'La Blanqueada',
    'La Comercial',
    'La Figurita',
    'La Paloma',
    'La Paloma - Tomkinson',
    'La Teja',
    'Larrañaga',
    'Las Acacias',
    'Las Canteras',
    'Lezica',
    'Lezica Melilla',
    'Malvin',
    'Malvin Norte',
    'Manga',
    'Manga Toledo Chico',
    'Marconi',
    'Maronas - Parque Guarani',
    'Maroñas',
    'Maroñas, Curva',
    'Melilla',
    'Mercado Modelo',
    'Mercado Modelo Y Bolivar',
    'Montevideo',
    'Nuevo Paris',
    'Pajas Blancas',
    'Palacio',
    'Palermo',
    'Parque Batlle',
    'Parque Batlle Villa Dolores',
    'Parque Rodo',
    'Paso De La Arena',
    'Paso De Las Duranas',
    'Paso Molino',
    'Paso de la Arena - Santiago Va',
    'Paso de la Arena - Santiago Vazquez',
    'Perez Castellanos',
    'Peñarol',
    'Piedras Blancas',
    'Playa Verde',
    'Pocitos',
    'Pocitos Nuevo',
    'Pque Batlle Villa Dolores',
    'Prado',
    'Prado - Nueva Savona',
    'Puerto',
    'Puerto Buceo',
    'Punta Carretas',
    'Punta De Rieles',
    'Punta Espinillo',
    'Punta Gorda',
    'Punta Rieles',
    'Punta Rieles Bella Italia',
    'Punta de Rieles - Bella Italia',
    'Reducto',
    'Santa Catalina',
    'Santiago Vazquez',
    'Sayago',
    'Toledo Chico',
    'Tres Cruces',
    'Tres Ombues Pblo Victoria',
    'Tres Ombúes',
    'Union',
    'Victoria',
    'Villa Biarritz',
    'Villa Dolores',
    'Villa Española',
    'Villa Garcia',
    'Villa Garcia Manga Rural',
    'Villa Munoz - Retiro - Goes',
    'Villa Muñoz',
    'Villa Muñoz Retiro',
    'Villa del Cerro',
  ],
  'Paysandú': [
    'Al Sur De Arroyo Sacra',
    'Algorta',
    'Araujo',
    'Arbolito (Totoral)',
    'Arroyo Malo',
    'Arroyo Negro',
    'Beisso',
    'Bella Vista',
    'Canada Del Pueblo',
    'Cangue',
    'Carumbe',
    'Casa Blanca',
    'Cerro Chato',
    'Chacras De Paysandu',
    'Chacras De Paysandu Norte',
    'Chacras De Paysandu Sur',
    'Chapicuy',
    'Colonia Arroyo Malo',
    'Colonia Cangue',
    'Colonia Juncal',
    'Colonia Las Delicias',
    'Colonia Paysandu',
    'Colonia Santa Blanca',
    'Colonia Uruguaya',
    'Constancia',
    'Costa De Sacra',
    'Cuchilla De Buricayupi',
    'Cuchilla De Fuego',
    'Cuchilla San Jose',
    'El Chaco',
    'El Duraznal',
    'El Eucaliptus',
    'El Horno',
    'El Tarugo',
    'Esperanza',
    'Estacion Porvenir',
    'Etchemendi',
    'Eucaliptus',
    'Gallinal',
    'Guaviyu De Quebracho',
    'Guayabos',
    'Guichón',
    'La Lata Ruta 3 (Km. 375)',
    'La Paz (Ruta 3 Km. 346)',
    'La Tentacion',
    'Las Flores',
    'Las Palmas',
    'Lorenzo Geyres',
    'Merinos',
    'Molles Grande',
    'Morato (Tres Arboles)',
    'Nuevo Paysandu',
    'Orgoroso',
    'P. Pandule',
    'Palmar Del Quebracho',
    'Pandule',
    'Parada Dayman',
    'Parada Pandule',
    'Parada Rivas',
    'Paso De Los Carros',
    'Paysandú',
    'Pblo Porvenir',
    'Perico Moreno',
    'Piedra Sola',
    'Piedras Coloradas',
    'Piñera',
    'Porvenir',
    'Pueblo Alonzo',
    'Pueblo Esperanza',
    'Pueblo Federacion',
    'Puntas De Arroyo Negro',
    'Puntas De Bacacua',
    'Puntas De Buricayupi',
    'Puntas De Cangue',
    'Puntas De Gualeguay',
    'Puntas De Las Isletas',
    'Quebracho',
    'Queguay Grande',
    'Queguayar',
    'Rabon',
    'San Felix',
    'San Francisco',
    'San Javier',
    'San Miguel',
    'Santa Kilda',
    'Sauce De Abajo',
    'Sauce Del Buricayupi',
    'Sauce Del Queguay',
    'Soto',
    'Tambores',
    'Termas De Almiron',
    'Termas De Guaviyu',
    'Tres Bocas',
    'Valdez',
    'Villa Maria (Tiatucura)',
    'Zeballos',
  ],
  'Rio Negro': [
    'Algorta',
    'Arroyo Negro',
    'Barrio Anglo',
    'Bellaco',
    'Canitas',
    'Caracoles',
    'Colonia El Ombu',
    'Colonia John F. Kennedy',
    'Colonia John Fitzgerald Kennedy',
    'Don Esteban',
    'El Abrojal',
    'El Ombu',
    'El Progreso',
    'El Surco',
    'Estacion Francia',
    'Estancia Vichadero',
    'Fray Bentos',
    'Grecco',
    'Isla De Arguelles',
    'La Arena',
    'La Coronilla',
    'La Florida',
    'La Palma',
    'La Union',
    'Las Canas',
    'Las Flores',
    'Las Fracciones',
    'Las Margaritas',
    'Los Arrayanes',
    'Los Mellizos',
    'Los Ranchos',
    'Mataojo',
    'Menafra',
    'Merinos',
    'Molles De Porrua',
    'Nuevo Berlín',
    'Ombucitos',
    'Palmar Grande',
    'Paso De Balbuena',
    'Paso De Leopoldo',
    'Paso De Los Cobres',
    'Paso De Los Mellizos',
    'Paso De Soca',
    'Paso Ramirez',
    'Pauru',
    'Porton Haedo',
    'Presidente San Martin',
    'Pte. San Martin',
    'Pueblo Grecco',
    'Punta Cebollati',
    'Punta De Carretera',
    'Puntas De Averias',
    'Rolon',
    'San Javier',
    'San Lorenzo',
    'Sanchez',
    'Sanchez Chico',
    'Santa Elisa',
    'Santa Isabel',
    'Santa Rosa',
    'Sarandi',
    'Sarandí De Navarro',
    'Sauce',
    'Tres Bocas',
    'Tres Quintas',
    'Uleste',
    'Valle De Soba',
    'Villa General Borges',
    'Villa María',
    'Yaguarete',
    'Young',
  ],
  Rivera: [
    'Abrojal',
    'Alborada',
    'Amarillo',
    'Arroyo Blanco',
    'Arroyo Sauzal',
    'Ataques',
    'Banado Del Chaja',
    'Barra De Ataques',
    'Barrio Recreo',
    'Batovi',
    'Berruti',
    'Blanquillos',
    'Buena Orden Al Norte',
    'Buena Union',
    'Capon Alto',
    'Caraguata',
    'Carpinteria',
    'Cerrillada',
    'Cerro Alegre',
    'Cerro Blanco De Cunapiru',
    'Cerro Caqueiro',
    'Cerro Chapeu',
    'Cerro Chato',
    'Cerro Pelado',
    'Cerro Pelado Al Este',
    'Cerro Solito',
    'Cerros Blancos',
    'Cerros De La Calera',
    'Chirca De Caraguata',
    'Coronilla',
    'Coronilla De Corrales',
    'Costas De Cunapiru',
    'Cruz De San Pedro',
    'Cuchilla De Tres Cerros',
    'Cuchilla De Yaguari',
    'Cuchilla Mangueras',
    'Cunapiru',
    'Curticeiras',
    'Curtume',
    'El Ceibo',
    'El Palmito',
    'Guaviyu',
    'Hospital',
    'La Caillava',
    'La Calera',
    'La Cerrillada',
    'La Chilca',
    'La Palma',
    'La Pedrera',
    'Lagos Del Norte',
    'Lagunon',
    'Lapuente',
    'Las Flores',
    'Laureles',
    'Los Potreros',
    'Lunarejo',
    'Mandubi',
    'Manuel Diaz',
    'Masoller',
    'Minas De Corrales',
    'Minas De Cunapiru (Usinas',
    'Minas De Cuñapiru (Usinas)',
    'Minas De Zapucay',
    'Moirones',
    'Parada Medina',
    'Paso Amarillo',
    'Paso Ataques',
    'Paso Casildo',
    'Paso De Arriera',
    'Paso De Ataques',
    'Paso De Frontera',
    'Paso De Gaire',
    'Paso De La Arena',
    'Paso De La Calera',
    'Paso Del Lagunon',
    'Paso Del Puerto',
    'Paso Del Tapado',
    'Paso Lapuente',
    'Paso Serpa',
    'Piedras Blancas',
    'Platon',
    'Pueblo De Los Santos',
    'Pueblo Socorro',
    'Puntas De Abrojal',
    'Puntas De Corrales',
    'Puntas De Cunapiru',
    'Puntas Del Sauzal',
    'Puntas Del Yaguari',
    'Rincon De Amarillo',
    'Rincon De Diniz',
    'Rincon De Los Castillos',
    'Rincon De Moraes',
    'Rincon De Rodriguez',
    'Rincon De Roland',
    'Rincon De Tres Cerros',
    'Rincon De Yaguari',
    'Rivera',
    'San Gregorio',
    'Santa Ernestina',
    'Santa Isabel',
    'Santa Teresa',
    'Sauce De Batovi',
    'Sauzal',
    'Segarra',
    'Tranqueras',
    'Tres Cerros',
    'Tres Cruces',
    'Tres Puentes',
    'Vichadero',
    'Villa Indart',
    'Yaguari',
    'Zanja Honda',
    'Zanja Honda De Tranqueras',
  ],
  Rocha: [
    '18 De Julio',
    '19 De Abril',
    'Abra De Alferez',
    'Aguas Dulces',
    'Alferez',
    'Antoniopolis',
    'Arachania',
    'Arbolito',
    'Balneario La Esmeralda',
    'Balneario Pueblo Nuevo',
    'Barra De Valizas',
    'Barra Del Chuy',
    'Barra Isla Negra',
    'Barrancas De La Coronilla',
    'Barrancas De La Pedrera',
    'Barrio Cardozo',
    'Barrio Carpacho',
    'Barrio Pereira',
    'Barrio Porvenir',
    'Barrio Torres',
    'Cabo Polonio',
    'Capacho',
    'Castillos',
    'Cebollatí',
    'Cerro De Los Rocha',
    'Cerro De Pescadores',
    'Chuy',
    'Colonia Greissing',
    'Costa Azul',
    'Costas De Cebollati',
    'Cuchilla De Garzon',
    'Cuchilla Del Arbolito',
    'Diamante De La Pedrera',
    'El Canelon',
    'El Chimango',
    'El Palmar',
    'Empalme De Velazquez',
    'Fortin De San Miguel',
    'Garzon Abajo',
    'Garzon Al Medio',
    'Garzon Arriba',
    'India Muerta',
    'Isla Negra',
    'Kilometro 18',
    'La Aguada',
    'La Aguada - Costa Azul',
    'La Aguada Y Costa Azul',
    'La Centinela',
    'La Coronilla',
    'La Esmeralda',
    'La Fortaleza De Santa Ter',
    'La Fortaleza De Santa Teresa',
    'La Palma',
    'La Paloma',
    'La Pedrera',
    'La Ribiera',
    'La Sierra',
    'La Tuna',
    'Laguna de Rocha',
    'Las Garzas',
    'Lascano',
    'Lomas',
    'Los Ajos',
    'Los Cerrillos',
    'Los Indios',
    'Oceania Del Polonio',
    'Oratorio',
    'Palmar',
    'Palmar De Castillos',
    'Palmares De La Coronilla',
    'Paralle',
    'Paso De Lopez',
    'Paso Del Banado',
    'Paso Del Ombu',
    'Paso Dona Rosa',
    'Pedrera Norte',
    'Picada Tolosa',
    'Plano 291',
    'Pueblo Nuevo',
    'Puente Valizas',
    'Puerto De Los Botes',
    'Puerto La Paloma',
    'Puimayen',
    'Punta Cebollati',
    'Punta Del Diablo',
    'Punta Palmar',
    'Punta Rubia',
    'Puntas De Don Carlos',
    'Quebracho',
    'Rincon De Los Olivera',
    'Rincon De Valizas',
    'Rocha',
    'Samuel',
    'San Antonio',
    'San Luis Al Medio',
    'San Sebastian',
    'San Sebastian De La Pedre',
    'San Sebastian De La Pedrera',
    'Santa Isabel De La Pedrera',
    'Santa Teresa De La Coronilla 1',
    'Santa Teresa De La Coronilla 2',
    'Sarandi De La India Muert',
    'Sarandi De La India Muerta',
    'Sauce De Rocha',
    'Sierra De Los Rocha',
    'Tajamares De La Pedrera',
    'Velázquez',
    'Vuelta Del Palmar',
  ],
  Salto: [
    'Albisu',
    'Arenitas Blancas',
    'Balneario Albisu',
    'Barrio Hipodromo',
    'Bella Vista',
    'Belén',
    'Biassini',
    'Bordenave',
    'Campo De Todos',
    'Carumbe',
    'Cayetano',
    'Celeste',
    'Cerrillada',
    'Cerrilladas De Saucedo',
    'Cerro Chato',
    'Cerro De Vera',
    'Cerros De Vera',
    'Chacras De Belen',
    'Chacras De Constitucion',
    'Colonia 18 De Julio',
    'Colonia Itapebí',
    'Colonia Lavalleja',
    'Colonia Osimani',
    'Colonia Rubio',
    'Constitución',
    'Corral De Piedra',
    'Corralito',
    'Cuchilla De Guaviyu',
    'Cuchilla Del Salto',
    'Dayman (Parada Dayman)',
    'El Espinillar',
    'El Mellado',
    'Ferreira',
    'Garibaldi',
    'Guaviyu De Arapey',
    'Itapebi',
    'La Bolsa',
    'La Bolsa 02',
    'La Bolsa 03',
    'La Caballada',
    'La Viticola',
    'Las Flores',
    'Laureles',
    'Lavalleja',
    'Lluveras',
    'Los Orientales',
    'Mataojito',
    'Mataojo',
    'Mataojo Grande',
    'Nueva Hesperides',
    'Olivera',
    'Osimani Y Llerena',
    'Palomas',
    'Parada Dayman',
    'Parada Herreria',
    'Parada Pandule',
    'Parque Jose Luis',
    'Paso Cementerio',
    'Paso De Las Piedras De Ar',
    'Paso De Las Piedras De Arerungua',
    'Paso Del Parque Del Dayman',
    'Paso Del Potrero',
    'Paso Del Tapado',
    'Paso Fialho',
    'Paso Nuevo Del Arapey',
    'Paso Valega',
    'Pepe Nunez',
    'Pueblo Cayetano',
    'Pueblo Farias',
    'Pueblo Fernandez',
    'Pueblo Quintana',
    'Pueblo Ramos',
    'Puntas De Alentín',
    'Puntas De Valentin',
    'Quintana',
    'Rincon De Valentin',
    'Russo',
    'Salto',
    'San Antonio',
    'San Mauricio',
    'Sarandi De Arapey',
    'Sarandí Del Arapey',
    'Sauce Chico',
    'Saucedo',
    'Sopas',
    'Talas De Itapebi',
    'Termas Del Arapey',
    'Termas Del Dayman',
    'Tomas Paz',
    'Toro Negro',
    'Tropezon',
    'Tropiezo',
    'Valentin Grande',
    'Villa Constitucion',
    'Yacuy',
    'Zanja De Alcain',
    'Zanja Del Tigre',
  ],
  'San Jose': [
    '18 De Julio',
    'Arroyo De La Virgen',
    'Arroyo Llano',
    'Autodromo',
    'Autodromo Nacional',
    'Balneario Kiyú',
    'Banado',
    'Bella Vista',
    'Boca Del Cufre',
    'Cagancha',
    'Cagancha Chico',
    'Canada Grande',
    'Capurro',
    'Carreta Quemada',
    'Ceramicas Del Sur',
    'Chamizo',
    'Ciudad Del Plata',
    'Cololo Tinosa',
    'Colonia Agraria Delta',
    'Colonia America',
    'Colonia Delta',
    'Colonia Doctor Bernardo Etchepare',
    'Colonia Dr. Bernardo Etch',
    'Colonia Dr. Bernardo Etchepare',
    'Colonia Fernandez Crespo',
    'Colonia Italia',
    'Colonia Juan Maria Perez',
    'Colonia San Joaquin',
    'Colonia Wilson',
    'Coronilla',
    'Costa Del Mauricio',
    'Costas De Pereira',
    'Costas Del Sauce',
    'Cruz De Los Caminos',
    'Cuchilla De Pereira',
    'Cuchilla Del Vichadero',
    'Cuchilla Seca',
    'Delta Del Tigre',
    'Delta El Tigre',
    'Ecilda Paullier',
    'Escudero',
    'Estacion Rodriguez',
    'Fajardo',
    'Fajina',
    'Gonzalez',
    'Guaycuru',
    'Ituzaingó',
    'Jesus Maria',
    'Juan Soler',
    'Juncal',
    'Kiyú - Ordeig',
    'La Boyada',
    'La Casilla',
    'La Cuchilla',
    'Laurel',
    'Libertad',
    'Mahoma',
    'Mal Abrigo',
    'Mangrullo',
    'Monte Grande',
    'Mundo Azul',
    'Mundo Azul Aguirre',
    'Orillas Del Plata',
    'Pachina',
    'Panta',
    'Pantanoso',
    'Parque Postel',
    'Parque Postel Cnel. Adria',
    'Parque Postel Cnel. Adrian Medina',
    'Paso Belastiqui',
    'Paso De Cames',
    'Paso De Las Piedras',
    'Paso De Mas',
    'Paso Del Carreton',
    'Paso Del Guaycuru',
    'Paso Del Rey',
    'Pavon',
    'Penino',
    'Perico Perez',
    'Picada Gambetta',
    'Playa Pascual',
    'Puntas De Cagancha',
    'Puntas De Canada Grande',
    'Puntas De Chamizo',
    'Puntas De Gregorio',
    'Puntas De Laurel',
    'Puntas De Tropa Vieja',
    'Puntas De Valdez',
    'Radial Ruta 3',
    'Rafael Perazza',
    'Raigon',
    'Rincon De Albano',
    'Rincon De Arazati',
    'Rincon De Arias',
    'Rincon De Buschental',
    'Rincon De Cufre',
    'Rincon De La Torre',
    'Rincon De Nazareth',
    'Rincon Del Pino',
    'Rincón De La Bolsa',
    'Rocho',
    'Rodriguez',
    'Safici',
    'San Fernando',
    'San Fernando Chico',
    'San Gregorio',
    'San Jose',
    'San José De Mayo',
    'Santa Monica',
    'Sauce',
    'Sauce Chico',
    'Scavino',
    'Tabarez',
    'Tala De Pereira',
    'Tranquera Colorada',
    'Tropas Viejas',
    'Tropezon',
    'Valdez Chico',
    'Villa María',
    'Villa Olimpica',
    'Villa Rives',
    'Villa Rodriguez',
    'Zanja Honda',
  ],
  Soriano: [
    'Agraciada',
    'Altos Del Perdido',
    'Ampliacion Larranaga',
    'Arenal Chico',
    'Arroyo Del Medio',
    'Arroyo Grande',
    'Asencio',
    'Azotea De Vera',
    'Bajos Del Perdido',
    'Bequelo',
    'Bizcocho',
    'Buena Vista',
    'Canada Magallanes',
    'Canada Paraguaya',
    'Cardona',
    'Castillos',
    'Cañada Nieto',
    'Cerro Alegre',
    'Cerro Vera',
    'Chacras De Dolores',
    'Chacras De Mercedes',
    'Cololo',
    'Colonia Concordia',
    'Colonia Diaz',
    'Colonia Larrañaga',
    'Colonia Santa Clara',
    'Colonia Uruguaya',
    'Coquimbo',
    'Corralito',
    'Costa Del Aguila',
    'Costas Del Perdido',
    'Cuatro Bocas De Buena Vis',
    'Cuatro Bocas De Buena Vista',
    'Cuchilla Del Corralito',
    'Cuchilla Del Perdido',
    'Cueva Del Tigre',
    'Dolores',
    'Duraznito',
    'Egaña',
    'El Aguila',
    'El Tala',
    'Espinillo',
    'Garula',
    'Grito De Asencio',
    'José Enrique Rodó',
    'La Concordia',
    'La Laguna',
    'La Loma',
    'La Palma',
    'La Tabla',
    'Lares',
    'Las Maulas',
    'Lata Del Perdido',
    'Maciel',
    'Mercedes',
    'Monzon',
    'Olivera',
    'Palmar',
    'Palmitas',
    'Palo Solo',
    'Parada Suarez',
    'Paso De La Arena',
    'Paso De Ramos',
    'Pedro Chico',
    'Perseverano',
    'Progreso',
    'Pueblo Palmar',
    'Puntas De Arenales',
    'Puntas De Durazno',
    'Puntas De San Salvador',
    'Puntas Del Tala',
    'Rincon De Canada Nieto',
    'Rincon De Cololo',
    'Rincon De Ruiz',
    'Risso',
    'San Dios',
    'San Martin',
    'Santa Blanca',
    'Santa Catalina',
    'Sarandi Chico',
    'Unidad Cooperaria No 1',
    'Villa Alejandrina',
    'Villa Darwin',
    'Villa De Soriano',
    'Villa Soriano',
    'Zanja Honda',
  ],
  'Tacuarembó': [
    'Achar',
    'Ansina',
    'Arroyo Del Medio',
    'Ataque',
    'Balneario Ipora',
    'Banado De Canas',
    'Banado De Rocha',
    'Barrio La Matutina',
    'Barrio Libertad',
    'Barrio Lopez',
    'Barrio Santangelo',
    'Barrio Torres',
    'Blanquillos',
    'Canada Del Estado',
    'Canas',
    'Caraguata Al Norte',
    'Cardoso',
    'Cardozo Chico',
    'Carpinteria',
    'Cerro Batovi',
    'Cerro Chato',
    'Cerro De Pastoreo',
    'Cerro De Pereira',
    'Cerro Del Arbolito',
    'Cerros De Clara',
    'Chamberlain',
    'Charata',
    'Churchill',
    'Cinco Sauces',
    'Clara',
    'Clavijo',
    'Colman',
    'Costas De Caraguata',
    'Costas De Tres Cruces',
    'Coyo Martinez',
    'Cruz De Los Caminos',
    'Cuchilla De La Casa De Pi',
    'Cuchilla De La Casa De Piedra',
    'Cuchilla De La Palma',
    'Cuchilla De Laureles',
    'Cuchilla De Peralta',
    'Cuchilla Del Ombu',
    'Curtina',
    'Echeverry',
    'El Empalme',
    'Estacion Menendez',
    'Frigorifico Modelo',
    'Heriberto',
    'La Aldea',
    'La Bolsa 01',
    'La Bolsa 02',
    'La Hilera',
    'La Palma',
    'La Pedrera',
    'Lambare',
    'Larrayos',
    'Las Arenas',
    'Las Chircas',
    'Las Pajas',
    'Las Toscas',
    'Las Toscas De Caraguata',
    'Laura',
    'Laureles',
    'Lavalleja',
    'Los Cerros',
    'Los Coitinhos',
    'Los Cuadrados',
    'Los Feos',
    'Los Furtados',
    'Los Garcia',
    'Los Gomez',
    'Los Laureles',
    'Los Malavares',
    'Los Ortices',
    'Los Rodriguez',
    'Los Rosanos',
    'Los Rosas',
    'Los Semper',
    'Los Vazquez',
    'Martinote',
    'Minuano',
    'Montevideo Chico',
    'Once Cerros',
    'Pampa',
    'Paso Bonilla',
    'Paso Casildo',
    'Paso De Ceferino',
    'Paso De Las Carretas',
    'Paso De Las Flores',
    'Paso De Las Toscas',
    'Paso De Los Novillos',
    'Paso De Los Toros',
    'Paso De Perez',
    'Paso Del Cerro',
    'Paso Del Medio',
    'Paso Hondo',
    'Paso Livindo',
    'Paso Victor',
    'Peralta',
    'Picada De Cuello',
    'Piedra Sola',
    'Pueblo Ansina',
    'Pueblo Centenario',
    'Pueblo Clavijo',
    'Pueblo De Arriba',
    'Pueblo Del Barro',
    'Punta De Carretera',
    'Puntas De Cinco Sauces',
    'Puntas De Laureles',
    'Rincon De Freitas',
    'Rincon De Giloca',
    'Rincon De La Aldea',
    'Rincon De La Laguna',
    'Rincon De Los Machado',
    'Rincon De Pereira',
    'Rincon De Zamora',
    'Rincon Del Bonete',
    'Rincón De La Bolsa',
    'Rivera Chico',
    'San Benito',
    'San Gregorio De Polanco',
    'San Joaquin',
    'Sauce De Batovi',
    'Sauce De Tranqueras',
    'Sauce Solo',
    'Sauce Solo Del Rio Negro',
    'Tacuarembo Chico',
    'Tacuarembó',
    'Tambores',
    'Tierras Coloradas',
    'Tres Guitarras',
    'Turupi',
    'Valle Edén',
    'Villa Ansina',
    'Zambullon',
    'Zapara',
    'Zapucay',
  ],
  'Treinta Y Tres': [
    'Acosta',
    'Arrayanes De Cebollati',
    'Arrayanes De Corral De Ce',
    'Arrayanes De Corral De Cebollati',
    'Arrocera Bonomo',
    'Arrocera El Tigre',
    'Arrocera La Catumbera',
    'Arrocera La Querencia',
    'Arrocera Las Palmas',
    'Arrocera Los Ceibos',
    'Arrocera Los Teros',
    'Arrocera Mini',
    'Arrocera Procipa',
    'Arrocera Rincon',
    'Arrocera San Fernando',
    'Arrocera Santa Fe',
    'Arrocera Zapata',
    'Arrozal Treinta Y Tres',
    'Averias',
    'Avestruz Chico',
    'Banado De Oro',
    'Barrio Abreu',
    'Canada Chica',
    'Canada De Las Piedras',
    'Canada Del Sauce',
    'Cerro Chato',
    'Cerro Pelado',
    'Cerros De Amaro',
    'Cipa Cebollati',
    'Cipa Olimar',
    'Cipa Secador',
    'Corrales De Cebollati',
    'Costas De Tacuari',
    'Costas Del Arroyo Malo',
    'Costas Del Sarandi',
    'Cuchilla De Dionisio',
    'Cuchilla De Olmos',
    'Ejido De Treinta Y Tres',
    'El Bellaco',
    'El Carmen',
    'El Catete',
    'Estacion Rincon',
    'Gral. Enrique Martinez',
    'Higuerones',
    'Isla Patrulla',
    'Julio Maria Sanz',
    'La Calavera',
    'La Calera',
    'La Charqueada',
    'La Lata',
    'Las Chacras',
    'Las Pavas',
    'Lechiguana De Corrales',
    'Los Ceibos',
    'Maria Isabel',
    'María Albina',
    'Mate Dulce',
    'Mendizabal',
    'Molles De Olimar',
    'Noques De Olimar Chico',
    'Olimar Grande',
    'Palo A Pique',
    'Panteon',
    'Paso Ancho',
    'Paso De Averias',
    'Paso De La Atahona',
    'Paso De La Laguna',
    'Paso De Piriz',
    'Paso Del Sauce',
    'Poblado Alonzo',
    'Puntas De Leoncho',
    'Puntas De Los Ceibos',
    'Puntas De Quebracho',
    'Puntas Del Oro',
    'Puntas Del Parao',
    'Rincon',
    'Rincon De Gadea',
    'Rincon De Iguini',
    'Rincon De Los Francos',
    'Rincon De Quintana',
    'Rincon De Urtubey',
    'Santa Clara De Olimar',
    'Sauce De Corrales',
    'Sierra Del Yerbal',
    'Siete Casas',
    'Treinta Y Tres',
    'Valentines',
    'Verde Alto',
    'Vergara',
    'Villa Passano',
    'Villa Sara',
    'Yerbal Chico',
    'Yerbalito',
  ],
}
const rules: PostalCodeRules = {
  country: 'URY',
  abbr: 'UY',
  postalCodeFrom: POSTAL_CODE,
  fields: [
    {
      hidden: true,
      name: 'country',
      maxLength: 100,
      label: 'country',
      size: 'medium',
    },
    {
      name: 'postalCode',
      maxLength: 50,
      label: 'postalCode',
      required: true,
      mask: '99999',
      regex: '^([\\d]{5})$',
      postalCodeAPI: false,
      forgottenURL:
        'http://geo.correo.com.uy/IsisBusquedaDireccionPlugin/cp.jsp',
      size: 'small',
      autoComplete: 'nope',
    },
    {
      name: 'street',
      label: 'street',
      required: true,
      size: 'xlarge',
    },
    {
      name: 'number',
      maxLength: 750,
      label: 'number',
      required: true,
      size: 'mini',
      autoComplete: 'nope',
    },
    {
      name: 'complement',
      maxLength: 750,
      label: 'complement',
      size: 'large',
    },
    {
      hidden: true,
      name: 'reference',
      maxLength: 750,
      label: 'reference',
      size: 'xlarge',
    },
    {
      name: 'neighborhood',
      maxLength: 750,
      label: 'neighborhood',
      size: 'large',
    },
    {
      name: 'city',
      maxLength: 750,
      label: 'city',
      required: true,
      size: 'large',
      options: getOneLevel(countryData),
    },
    {
      name: 'state',
      maxLength: 750,
      label: 'state',
      required: true,
      size: 'medium',
      options: getTwoLevels(countryData),
    },
  ],
  geolocation: {
    postalCodeAPI: false,
    cityLevelTwo: ['administrative_area_level_2'],
    cityLevelOne: ['locality', 'sublocality', 'administrative_area_level_3'],
    neighborhood: ['neighborhood', 'sublocality_level_1'],
    stateTypes: ['administrative_area_level_1'],
  },
  summary: [
    [{ name: 'street' }, { name: 'number' }],
    [{ name: 'complement' }],
    [{ name: 'neighborhood' }, { name: 'city' }],
    [{ name: 'state' }],
  ],
}

export default rules
